# Generated by Django 3.2.18 on 2023-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.TextField(max_length=24)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
