# Generated by Django 3.2.18 on 2023-05-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_email_user_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('isPublic', models.BooleanField(default=False)),
                ('likes', models.IntegerField()),
                ('authorId', models.IntegerField()),
                ('authorName', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.BooleanField(default=False)),
                ('fontSize', models.CharField(max_length=255)),
                ('fontColor', models.CharField(max_length=255)),
                ('fontFamily', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
