# Generated by Django 3.2.18 on 2023-05-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230503_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('userId', models.IntegerField()),
                ('createdAt', models.CharField(max_length=255)),
                ('diary_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
