# Generated by Django 3.2.18 on 2023-05-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_diary_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='body',
            field=models.CharField(default='', max_length=255),
        ),
    ]
