# Generated by Django 3.2.18 on 2023-05-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_diary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='diary_id',
            new_name='diary',
        ),
    ]
